version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - ceph
    networks:
      default:
      ceph:
        ipv4_address: 10.28.0.20
    volumes_from:
      - ceph

  ceph:
    image: ceph/demo:tag-build-master-jewel-ubuntu-14.04
    environment:
      - MON_IP=10.28.0.10
      - CEPH_PUBLIC_NETWORK=10.28.0.0/24
    networks:
      ceph:
        ipv4_address: 10.28.0.10
    volumes:
      - /etc/ceph

# Default network (required by the Ceph cluster, as we need to pass our own IP as env. variable)
networks:
  ceph:
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/24
